// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful"

export interface ICallToActionFields {
  /** Label */
  label: string

  /** URL */
  url: string

  /** Style */
  style?: "Primary" | "Secondary" | "Text Link" | undefined
}

/** A reusable button or link wrapper */

export interface ICallToAction extends Entry<ICallToActionFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: "callToAction"
        linkType: "ContentType"
        type: "Link"
      }
    }
  }
}

export interface IComponentFooterFields {
  /** Internal Name */
  internalName: string

  /** Headline */
  headline?: string | undefined

  /** Text */
  text?: string | undefined

  /** Primary CTA */
  primaryCta?: ICallToAction | undefined
}

/** Footer section with CTA */

export interface IComponentFooter extends Entry<IComponentFooterFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: "componentFooter"
        linkType: "ContentType"
        type: "Link"
      }
    }
  }
}

export interface IComponentHeroFields {
  /** Internal Name */
  internalName: string

  /** Tagline */
  tagline?: string | undefined

  /** Headline */
  headline: string

  /** Subline */
  subline?: string | undefined

  /** Background Image */
  backgroundImage?: Asset | undefined

  /** Call To Actions */
  ctas?: ICallToAction[] | undefined
}

/** Hero section with background image and CTAs */

export interface IComponentHero extends Entry<IComponentHeroFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: "componentHero"
        linkType: "ContentType"
        type: "Link"
      }
    }
  }
}

export interface IComponentPromotionGridFields {
  /** Internal Name */
  internalName: string

  /** Headline */
  headline?: string | undefined

  /** Section CTA */
  cta?: ICallToAction | undefined

  /** Promotions */
  promotions?: IPromotion[] | undefined
}

/** Grid layout for promotions */

export interface IComponentPromotionGrid extends Entry<IComponentPromotionGridFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: "componentPromotionGrid"
        linkType: "ContentType"
        type: "Link"
      }
    }
  }
}

export interface IPageFields {
  /** Slug */
  slug: string

  /** SEO Title */
  seoTitle?: string | undefined

  /** SEO Description */
  seoDescription?: string | undefined

  /** Sections */
  sections?: (IComponentHero | IComponentPromotionGrid | IComponentFooter)[] | undefined
}

/** A landing page composed of sections */

export interface IPage extends Entry<IPageFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: "page"
        linkType: "ContentType"
        type: "Link"
      }
    }
  }
}

export interface IPromotionFields {
  /** Internal Name */
  internalName: string

  /** Title */
  title: string

  /** Description */
  description?: string | undefined

  /** Image */
  image?: Asset | undefined

  /** Badge */
  badge?: string | undefined

  /** Link URL */
  link?: string | undefined

  /** Start Date */
  startDate?: string | undefined

  /** End Date */
  endDate?: string | undefined
}

/** Reusable promotion data (e.g. Washing Machine Promo) */

export interface IPromotion extends Entry<IPromotionFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: "promotion"
        linkType: "ContentType"
        type: "Link"
      }
    }
  }
}

export type CONTENT_TYPE =
  | "callToAction"
  | "componentFooter"
  | "componentHero"
  | "componentPromotionGrid"
  | "page"
  | "promotion"

export type IEntry =
  | ICallToAction
  | IComponentFooter
  | IComponentHero
  | IComponentPromotionGrid
  | IPage
  | IPromotion

export type LOCALE_CODE = "en-US"

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US"
